python3-checks:
  image: $CI_REGISTRY/gdraheim/ci_image_python3
  script:
    - make style || true
    - make type
    - make tests
    - find . -name '*.xml'
  artifacts:
    reports:
      junit: "*/TEST-*.xml"

